version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: roommate-db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - housemate-net
    restart: unless-stopped

  housemate-be:
    build: .
    image: ghcr.io/sahinokdem/matie:latest
    container_name: housemate-backend
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/${POSTGRES_DB}
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
    depends_on:
      - postgres
    networks:
      - housemate-net
    restart: unless-stopped

  nginx:
    image: nginx:1.27-alpine
    container_name: housemate-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      # FE Dockerize edilene kadar aşağıdaki satırı kapalı tutabilirsin 
      # veya sunucuda 'frontend/dist' klasörünü manuel oluşturmalısın.
      # - ./frontend/dist:/usr/share/nginx/html:ro
      - nginx_cache:/var/cache/nginx
    depends_on:
      - housemate-be
    networks:
      - housemate-net
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /root/.docker/config.json:/config.json
    environment:
      - DOCKER_API_VERSION=1.44
    command: --interval 30 --cleanup

volumes:
  pgdata:
  nginx_cache:

networks:
  housemate-net: